"use client";

import { decodeAiReview } from "@/lib/aiReview";
import { Card, CardHeader, CardBody, Badge, Notice } from "@/components/ui";

export function AIReviewDisplay({ aiReview }: { aiReview: `0x${string}` }) {
  const decoded = decodeAiReview(aiReview);
  if (!decoded) return null;

  const { raw, parsed } = decoded;

  return (
    <Card>
      <CardHeader
        title="AI review"
        subtitle="Generated by Ritual AI from all submissions."
        action={
          parsed ? (
            <Badge tone="indigo">Recommends #{parsed.winnerIndex}</Badge>
          ) : (
            <Badge tone="amber">Unparsed</Badge>
          )
        }
      />
      <CardBody className="space-y-3">
        {parsed ? (
          <>
            {parsed.ranking.length > 0 && (
              <div className="overflow-hidden rounded-xl border border-line">
                <table className="w-full text-left text-sm">
                  <thead className="bg-cream/60 font-mono text-xs uppercase tracking-wide text-muted">
                    <tr>
                      <th className="px-3 py-2 font-medium">#</th>
                      <th className="px-3 py-2 font-medium">Score</th>
                      <th className="px-3 py-2 font-medium">Reason</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[...parsed.ranking]
                      .sort((a, b) => b.score - a.score)
                      .map((r) => (
                        <tr
                          key={r.index}
                          className={`border-t border-line ${
                            r.index === parsed.winnerIndex
                              ? "bg-brand/[0.06]"
                              : ""
                          }`}
                        >
                          <td className="px-3 py-2 font-mono text-ink">
                            {r.index}
                            {r.index === parsed.winnerIndex && (
                              <span className="ml-1 text-brand">★</span>
                            )}
                          </td>
                          <td className="px-3 py-2 font-mono font-medium text-ink">
                            {r.score}
                          </td>
                          <td className="px-3 py-2 text-muted">{r.reason}</td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              </div>
            )}

            {parsed.summary && (
              <div className="rounded-xl bg-cream/50 px-3 py-2 text-sm text-ink">
                <span className="text-muted">Summary: </span>
                {parsed.summary}
              </div>
            )}
          </>
        ) : (
          <>
            <Notice tone="amber">
              Couldn&apos;t parse the AI review as JSON. Showing the raw response.
            </Notice>
            <pre className="max-h-72 overflow-auto rounded-xl bg-ink/5 p-3 font-mono text-xs text-ink whitespace-pre-wrap break-words">
              {raw}
            </pre>
          </>
        )}
      </CardBody>
    </Card>
  );
}
